spring:
  kafka:
    # pod 실행 중인 service 이름으로 변경 (localhost X)
    kafka-server: kafka-service:9092

# Feign + CircuitBreaker 트랜젝션 처리
feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        failure-rate-threshold: 40
        wait-duration-in-open-state: 10s